apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
  namespace: default
  labels:
    app: hello-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
        - name: hello-server
          image: hello-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: hello-server-config-map
              mountPath: "/config"
              readOnly: true
            - name: hello-server-secret
              mountPath: "/secrets"
              readOnly: true
            - name: host-volume
              mountPath: /etc-on-host
              readOnly: true
      volumes:
        - name: hello-server-config-map
          configMap:
            name: hello-server-config-map
        - name: hello-server-secret
          secret:
            secretName: hello-server-secret
        - name: host-volume
          # mount /etc, but only if that directory already exists
          hostPath:
            path: /etc # directory location on host
            type: Directory # this field is optional
#          env:
#            - name: ENV_VARIABLE
#              valueFrom:
#                secretKeyRef:
#                  name: my-secret
#                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: hello-server
  namespace: default
spec:
  selector:
    app: hello-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-server-config-map
data:
  overrides.conf: |
    urlFromConfigMap: "this is a value from the config map"
    include file("/secrets/overrides.conf")

---
apiVersion: v1
kind: Secret
metadata:
  name: hello-server-secret
type: Opaque
data:
  # base64(secret = "this value is from secret")
  overrides.conf: |
    c2VjcmV0ID0gInRoaXMgdmFsdWUgaXMgZnJvbSBzZWNyZXQi


#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: hello-server
#  namespace: default
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#spec:
#  rules:
#    - host: "prasata.cloudfarms.com"
#      http:
#        paths:
#          - pathType: Prefix
#            path: /
#            backend:
#              service:
#                name: hello-server
#                port:
#                  number: 8080